### ISSUE TITLE
Browser completely grey when rounded corners disabled and no transparency

### ISSUE THREAD

**Issue by rustermi** [Loskir/EdgyArc-fr#4]
When I have
* `uc.tweak.rounded-corners`: `false`
* `af.edgyarc.macos-translucent`: `false`
my content disappears:
![Kapture 2024-09-10 at 22 37 25](https://github.com/user-attachments/assets/77f4749b-d022-4445-9b11-9c1086d49241)

This happens since ef7abb43ba75892067071609f303701efc4efaab

**Comment by Loskir** [comment]
That's interesting. Which version of FF are you on?

**Comment by rustermi** [comment]
for completeness: 131.0b5 (developer edition)

**Comment by Loskir** [comment]
Thank you for the report! Looks fixed now
