### ISSUE TITLE
Unrounded window corners on KDE Plasma 6.1

### ISSUE THREAD

**Issue by alixyz-1** [Loskir/EdgyArc-fr#6]
Window corners appear sharp and square around the window on a fresh Firefox profile installed on KDE Plasma 6.1
![image](https://github.com/user-attachments/assets/d4902303-8428-4b37-9834-053a9caa3f7b)

Expected behaviour is like that of edge-frfox (as shown below). I see that edge-frfox uses the "widget.gtk.rounded-bottom-corners.enabled" flag to fix rounding on bottom of window also.
![image](https://github.com/user-attachments/assets/21256a94-9a27-403e-ade9-128a685c2387)

Not sure if a bug or a feature, as I was previously using KDE-rounded-corners to render corners on every window (but I cannot anymore as it's incompatible with hidpi scaling)

- OS: Manjaro Linux
- Desktop: KDE Plasma 6.1
- Browser: Firefox 131.0.2

**Comment by Loskir** [comment]
Hello! Hope it's fixed now
