### ISSUE TITLE
Address bar extends full size of the screen on ff 133.0b1

### ISSUE THREAD

**Issue by cornedor** [Loskir/EdgyArc-fr#7]
Address bar extends full size of the screen after Firefox update

**Screenshots**

![image](https://github.com/user-attachments/assets/fc8317df-d0fa-459d-9ab8-5ad9ac9d4be3)

**Desktop (please complete the following information):**

- OS: [e.g. iOS] MacOS
- Browser [e.g. chrome, safari] Firefox
- Version [e.g. 22] 133.0b1

**Additional context**

**Comment by Loskir** [comment]
Hi! Cannot reproduce this issue on 133.0b5
Could you share your configuration?

**Comment by cornedor** [comment]
The issue persists with a new profile with minimal config changes.

[3gmjtjs0.test-profile.zip](https://github.com/user-attachments/files/17658093/3gmjtjs0.test-profile.zip)

**Comment by Loskir** [comment]
Thank you for reporting!

**Comment by cornedor** [comment]
Thanks for fixing :)
